development:
  secret_key_base: 2f94601049a14193ca603923d770a0189c82d3746fbdb3aa472780791dc1e0c4048f473a1004a829a10d0aaa0abfc0f061282a51eba05af926849d772bac022a
  recaptcha_site_key: <%= ENV["6LcMJE4UAAAAAEi3gQtWLbJriC-i5gh-8fom189R"] %>
  recaptcha_secret_key: <%= ENV["6LcMJE4UAAAAAPKZFGfhcwWTLTKlIaFD7N6xJC9T"] %>

test:
  secret_key_base: 58150241e15c621ffba28e32cd67928e54a78dfe722371c3e52b740eb7ebb5c05a02cd10071b3661af6771d1aca8f41453f6315e807c61d3f8c5e8e1b8c7adb7

 #Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_site_key: <%= ENV["6LcMJE4UAAAAAEi3gQtWLbJriC-i5gh-8fom189R"] %>
  recaptcha_secret_key: <%= ENV["6LcMJE4UAAAAAPKZFGfhcwWTLTKlIaFD7N6xJC9T"] %>
  
